# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --production --ignore-scripts

# Copy source files and ts config
COPY tsconfig.json ./
COPY src ./src

# Build the project (TypeScript compilation)
RUN npm install --ignore-scripts && npm run build

# Copy additional files if necessary (corpora.txt is copied to dist during postbuild)

EXPOSE 3000

CMD [ "node", "dist/index.js" ]
